# -*- coding: utf-8 -*-
"""seleksi_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYSBexEYeG2TbldfIZcx2g0-hyW_j0wU
"""

kurs = []
pilih = 7
while (pilih != 0):
  print("Menu")
  print("1. Isi Data")
  print("2. Tampilkan Data")
  print("3. Hapus Data")
  print("4. Kurs Terkecil")
  print("5. Kurs Terbesar")
  print("6. Rata-Rata")
  print("0. Keluar")
  pilih=int(input("Pilih Menu : "))
  if (pilih == 1):
    n = len(kurs)
    a = int(input("Isi Kurs Ke- "+str(n) + " : "))
    kurs.append(a)
  elif (pilih == 2):
    for i in range(0,len(kurs)):
      print("Kurs Ke - " + str(i) + " : " + str(kurs[i]))
  elif (pilih == 3):
    for i in range(0,len(kurs)):
      print("Kurs Ke - " + str(i) + " : " + str(kurs[i]))
    hapus = int(input("Kurs Ke Berapa yang Ingin Dihapus : "))
    kurs.pop(hapus)
  elif (pilih == 4):
    terkecil = kurs[0]
    for x in range (0,len(kurs)):
      if terkecil > kurs [x]:
        terkecil = kurs[x]
    print("Nilai Terkecil Adalah : " + str(terkecil))
  elif (pilih == 5):
    terbesar = kurs[0]
    for x in range (0,len(kurs)):
      if terbesar < kurs [x]:
        terbesar = kurs[x]
    print("Nilai Terbesar Adalah : " + str(terbesar))
  elif (pilih == 6):
    rata = sum(kurs) / len(kurs)
    print("Rata-Rata Data Kurs Adalah : " + str(rata))